# Generated by Django 3.0.6 on 2020-08-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_invitation_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='invivation',
            name='is_disable',
            field=models.BooleanField(default=False),
        ),
    ]
