# Generated by Django 3.0.6 on 2020-08-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_all_parent_nodes_balance_gift_record_points_criteria_points_holder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift_record',
            name='TIME',
            field=models.TimeField(default='02:43:24'),
        ),
    ]
