# Generated by Django 3.0.6 on 2020-08-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_auto_20200812_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='points',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gift_record',
            name='TIME',
            field=models.TimeField(default='02:56:41'),
        ),
    ]
