# Generated by Django 3.0.6 on 2020-08-12 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0014_auto_20200812_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift_record',
            name='TIME',
            field=models.TimeField(default='04:09:42'),
        ),
        migrations.CreateModel(
            name='tree_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_root', models.BooleanField(default=False)),
                ('is_out', models.BooleanField(default=True)),
                ('left_child', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node_left_child', to='application.tree_data')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_node', to=settings.AUTH_USER_MODEL)),
                ('right_child', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node_right_child', to='application.tree_data')),
            ],
        ),
    ]
