# Generated by Django 3.0.6 on 2020-08-12 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_auto_20200812_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift_record',
            name='TIME',
            field=models.TimeField(default='06:17:13'),
        ),
        migrations.AlterField(
            model_name='tree_data',
            name='left_child',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node_left_child', to='application.tree_data'),
        ),
        migrations.AlterField(
            model_name='tree_data',
            name='parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node_parent', to='application.tree_data'),
        ),
        migrations.AlterField(
            model_name='tree_data',
            name='right_child',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node_right_child', to='application.tree_data'),
        ),
    ]
