# Generated by Django 3.0.6 on 2020-08-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_auto_20200812_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift_record',
            name='TIME',
            field=models.TimeField(default='06:21:48'),
        ),
    ]
