# Generated by Django 3.0.6 on 2020-08-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0018_auto_20200812_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift_record',
            name='TIME',
            field=models.TimeField(default='06:40:16'),
        ),
        migrations.AlterField(
            model_name='tree_data',
            name='is_out',
            field=models.BooleanField(default=False),
        ),
    ]
