# Generated by Django 3.0.6 on 2020-08-16 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0021_auto_20200815_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift_record',
            name='DATE',
            field=models.DateField(default='2020-08-16'),
        ),
        migrations.AlterField(
            model_name='gift_record',
            name='FROM',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider', to='application.tree_data'),
        ),
        migrations.AlterField(
            model_name='gift_record',
            name='TIME',
            field=models.TimeField(default='10:58:05'),
        ),
        migrations.AlterField(
            model_name='gift_record',
            name='TO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='application.tree_data'),
        ),
        migrations.AlterField(
            model_name='points_holder',
            name='points',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='points_holder',
            name='which_tree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.tree_data'),
        ),
        migrations.CreateModel(
            name='sending_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATE', models.DateField(default='2020-08-16')),
                ('TIME', models.TimeField(default='10:58:05')),
                ('holding_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.points_holder')),
            ],
        ),
    ]
