# Generated by Django 3.0.6 on 2020-08-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0023_auto_20200816_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift_record',
            name='TIME',
            field=models.TimeField(default='12:50:17'),
        ),
        migrations.AlterField(
            model_name='sending_history',
            name='TIME',
            field=models.TimeField(default='12:50:17'),
        ),
    ]
